spring.datasource.url=jdbc:postgresql://localhost:5432/logsdb
spring.datasource.username=alura
spring.datasource.password=alura

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update